import { Link } from 'react-router-dom';
const services = [
  {icon:'bi-people',title:'Global Membership',text:'Join a trusted network of publishers, editors, and scholarly organizations.',to:'/membership'},
  {icon:'bi-bar-chart-line',title:'Journal Ranking',text:'Transparent evaluation designed to recognize quality and publishing impact.',to:'/journal-ranking'},
  {icon:'bi-shield-check',title:'Publishing Excellence',text:'Strengthen editorial quality, peer review, ethics, and international publishing standards.',to:'/role/publishing-excellence'}
];
export default function Home(){return <>
  <section className="hero"><div className="hero-orb one"/><div className="hero-orb two"/><div className="container position-relative"><div className="row align-items-center min-vh-hero">
    <div className="col-lg-7"><span className="eyebrow-light"><i className="bi bi-stars me-2"/>Advancing scholarly publishing worldwide</span><h1>Where publishing<br/><em>standards rise.</em></h1><p>We unite journal publishers, strengthen research integrity, and expand the global reach of credible scholarly knowledge.</p><div className="d-flex flex-wrap gap-3"><Link to="/membership/apply" className="btn btn-accent btn-lg">Join the Association <i className="bi bi-arrow-right ms-2"/></Link><Link to="/about/ijpass" className="btn btn-outline-light btn-lg">Discover IJPAss</Link></div>
    <div className="trust-row"><span><b>Global</b> community</span><span><b>Ethical</b> standards</span><span><b>Open</b> knowledge</span></div></div>
    <div className="col-lg-5 d-none d-lg-block"><div className="hero-visual"><div className="globe-ring"><i className="bi bi-globe-americas"/></div><div className="float-card card-one"><i className="bi bi-patch-check-fill"/><span><b>Trusted Standards</b><small>Research integrity</small></span></div><div className="float-card card-two"><i className="bi bi-journals"/><span><b>Quality Journals</b><small>Global visibility</small></span></div></div></div>
  </div></div></section>
  <section className="stat-strip"><div className="container"><div className="row text-center"><div className="col-4"><strong>Global</strong><span>Publisher Network</span></div><div className="col-4"><strong>Rigorous</strong><span>Quality Framework</span></div><div className="col-4"><strong>Future-ready</strong><span>Digital Publishing</span></div></div></div></section>
  <section className="section-space"><div className="container"><div className="row align-items-end mb-5"><div className="col-lg-7"><span className="eyebrow">What we do</span><h2>A stronger ecosystem for <span>scholarly publishing.</span></h2></div><div className="col-lg-5"><p className="lead-copy">Practical services and internationally aligned standards for publishers at every stage of their journey.</p></div></div><div className="row g-4">{services.map((s,i)=><div className="col-md-4" key={s.title}><Link to={s.to} className="service-card"><span className="service-number">0{i+1}</span><div className="icon-box"><i className={`bi ${s.icon}`}/></div><h3>{s.title}</h3><p>{s.text}</p><span className="card-link">Explore service <i className="bi bi-arrow-up-right"/></span></Link></div>)}</div></div></section>
  <section className="standards section-space"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-6"><div className="image-composition"><div className="pattern"/><div className="quote-panel"><i className="bi bi-quote"/><p>Credibility is earned through transparency, integrity, and consistent publishing excellence.</p><span>IJPAss guiding principle</span></div></div></div><div className="col-lg-6"><span className="eyebrow">Our purpose</span><h2>Standards that build <span>lasting trust.</span></h2><p className="lead-copy">IJPAss champions responsible practices that help quality research travel further and create meaningful impact.</p><ul className="check-list"><li>Publisher capacity and professional development</li><li>Transparent journal evaluation and recognition</li><li>Responsible open-access and digital-first practices</li><li>International cooperation across disciplines</li></ul><Link to="/role" className="text-link">See our role in publishing <i className="bi bi-arrow-right"/></Link></div></div></div></section>
  <section className="cta-band"><div className="container text-center"><span className="eyebrow-light">Become part of the movement</span><h2>Shape the future of scholarly publishing.</h2><p>Connect, contribute, and grow with an international association committed to excellence.</p><Link className="btn btn-accent btn-lg" to="/membership/apply">Apply for membership <i className="bi bi-arrow-right ms-2"/></Link></div></section>
  </>}
