import { useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { api } from '../lib/auth';
import AdminPagination, { ADMIN_PAGE_SIZE } from './AdminPagination';
import AdminTableControls from './AdminTableControls';
import ManuscriptAuthorPicker, { type ManuscriptAuthorAssignment } from './ManuscriptAuthorPicker';

const schema = z.object({ articleCode:z.string().trim().min(1,'Enter the article code').max(45), articleTitle:z.string().trim().min(2,'Enter the article title'), journalId:z.string().min(1,'Select a source'), subjectAreaId:z.string().min(1,'Select a subject area'), authorId:z.string(), primaryAuthorProfileId:z.string().refine(v=>!v||/^\d+$/.test(v),'Enter a valid profile ID'), volume:z.string().max(45), issue:z.string().max(45), pages:z.string().max(100), publicationMonth:z.string().max(45), publicationYear:z.string().refine(v=>!v||/^\d{4}$/.test(v),'Enter a four-digit year'), doi:z.string().max(255), articleLink:z.string().refine(v=>!v||/^(https?:\/\/)?[^\s.]+\.[^\s]+$/i.test(v),'Enter a valid link'), abstract:z.string(), keywords:z.string() });
type Values=z.infer<typeof schema>;
type Source={id:number;title:string};
type SubjectArea={id:number;majorSubject:string;classificationName:string;subjectArea:string};
type Manuscript={id:number;articleCode:string;articleTitle:string;journalId:number;journalTitle:string;subjectAreaId:number|null;subjectArea:string|null;subjectClassification:string|null;authorId:number;primaryAuthorProfileId:number|null;authors:string|null;authorAssignments?:Array<ManuscriptAuthorAssignment&{authorOrder:number;authorDataId:number;affiliationId:number|null}>;volume:string|null;issue:string|null;pages:string|null;publicationMonth:string|null;publicationYear:number|null;doi:string|null;articleLink:string|null;abstract:string|null;keywords:string|null;referenceCount:number};
type Pagination={page:number;pageSize:number;totalRecords:number;totalPages:number};
const empty:Values={articleCode:'',articleTitle:'',journalId:'',subjectAreaId:'',authorId:'',primaryAuthorProfileId:'',volume:'',issue:'',pages:'',publicationMonth:'',publicationYear:'',doi:'',articleLink:'',abstract:'',keywords:''};

export default function ManuscriptManager({mode='list'}:{mode?:'list'|'form'}){
  const navigate=useNavigate(), location=useLocation();
  const [records,setRecords]=useState<Manuscript[]>([]),[sources,setSources]=useState<Source[]>([]),[subjectAreas,setSubjectAreas]=useState<SubjectArea[]>([]),[subjectAreaQuery,setSubjectAreaQuery]=useState(''),[editingId,setEditingId]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deletingId,setDeletingId]=useState<number|null>(null),[query,setQuery]=useState(''),[sort,setSort]=useState('newest'),[page,setPage]=useState(1),[pagination,setPagination]=useState<Pagination>({page:1,pageSize:20,totalRecords:0,totalPages:1}),[authorAssignments,setAuthorAssignments]=useState<ManuscriptAuthorAssignment[]>([]);
  const {register,handleSubmit,reset,watch,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:empty});
  const load=useCallback(()=>{setLoading(true);setError('');return api.get<{manuscripts:Manuscript[];pagination:Pagination}>('/admin/manuscripts',{params:{q:query.trim()||undefined,page,sort}}).then(({data})=>{setRecords(data.manuscripts);setPagination(data.pagination)}).catch(()=>setError('Unable to load manuscripts.')).finally(()=>setLoading(false))},[page,query,sort]);
  useEffect(()=>{if(mode!=='list')return;const timer=window.setTimeout(()=>void load(),query?300:0);return()=>window.clearTimeout(timer)},[load,mode,query]);
  useEffect(()=>{if(mode!=='form')return;let cancelled=false;const id=Number(new URLSearchParams(location.search).get('edit'));setLoading(true);Promise.all([api.get<{sources:Source[]}>('/admin/manuscript-sources'),api.get<{subjectAreas:SubjectArea[]}>('/admin/manuscript-subject-areas'),id?api.get<{manuscript:Manuscript}>(`/admin/manuscripts/${id}`):Promise.resolve(null)]).then(([sourceResponse,subjectAreaResponse,detailResponse])=>{if(cancelled)return;setSources(sourceResponse.data.sources);setSubjectAreas(subjectAreaResponse.data.subjectAreas);if(detailResponse){const r=detailResponse.data.manuscript;setEditingId(r.id);setAuthorAssignments((r.authorAssignments||[]).filter(author=>author.affiliationId).map(author=>({...author,affiliationId:Number(author.affiliationId),designation:author.designation||''})));reset({articleCode:r.articleCode,articleTitle:r.articleTitle,journalId:String(r.journalId),subjectAreaId:r.subjectAreaId?String(r.subjectAreaId):'',authorId:String(r.authorId),primaryAuthorProfileId:r.primaryAuthorProfileId?String(r.primaryAuthorProfileId):'',volume:r.volume||'',issue:r.issue||'',pages:r.pages||'',publicationMonth:r.publicationMonth||'',publicationYear:r.publicationYear?String(r.publicationYear):'',doi:r.doi||'',articleLink:r.articleLink||'',abstract:r.abstract||'',keywords:r.keywords||''})}else{setEditingId(null);setAuthorAssignments([]);reset(empty)}}).catch(()=>setError('Unable to load the manuscript form data.')).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[location.search,mode,reset]);
  const changeQuery=(value:string)=>{setQuery(value);setPage(1)},changeSort=(value:string)=>{setSort(value);setPage(1)};
  const submit=async(v:Values)=>{setError('');if(!authorAssignments.length){setError('Add at least one author and select an affiliation.');return;}const payload={...v,journalId:Number(v.journalId),subjectAreaId:Number(v.subjectAreaId),authorId:v.authorId?Number(v.authorId):'',primaryAuthorProfileId:v.primaryAuthorProfileId?Number(v.primaryAuthorProfileId):'',publicationYear:v.publicationYear?Number(v.publicationYear):'',authors:authorAssignments.map(author=>({authorProfileId:author.authorProfileId,affiliationId:author.affiliationId,designation:author.designation}))};try{await (editingId?api.put(`/admin/manuscripts/${editingId}`,payload):api.post('/admin/manuscripts',payload));navigate('/admin/manuscripts')}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||'Unable to save the manuscript. Check the article code, source, subject area, and author details.')}};
  const remove=async(r:Manuscript)=>{if(!window.confirm(`Delete “${r.articleTitle}”? Its authorship links and ${r.referenceCount} reference record(s) will also be deleted.`))return;setDeletingId(r.id);setError('');try{const response=await api.delete<{message:string}>(`/admin/manuscripts/${r.id}`);setNotice(response.data.message);await load()}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||'Unable to delete the manuscript.')}finally{setDeletingId(null)}};
  const selectedSubjectAreaId=watch('subjectAreaId'),subjectSearch=subjectAreaQuery.trim().toLocaleLowerCase();
  const filteredSubjectAreas=subjectAreas.filter(subject=>String(subject.id)===selectedSubjectAreaId||!subjectSearch||[subject.majorSubject,subject.classificationName,subject.subjectArea].some(value=>value.toLocaleLowerCase().includes(subjectSearch)));
  return <section><div className="manager-heading"><div><span className="eyebrow">Super Admin controls</span><h2>{mode==='form'?(editingId?'Edit Manuscript':'Add New Manuscript'):'Manuscript List'}</h2><p>Manage indexed manuscript records and publication metadata.</p></div>{mode==='list'?<button className="btn btn-primary" onClick={()=>navigate('/admin/manuscripts/addnew')}><i className="bi bi-plus-lg me-2"/>Add New</button>:<button className="btn btn-outline-secondary" onClick={()=>navigate('/admin/manuscripts')}><i className="bi bi-arrow-left me-2"/>Back to list</button>}</div>
  {mode==='form'&&<div className="admin-form-card"><div className="admin-panel-heading"><span className="form-icon"><i className="bi bi-file-earmark-richtext"/></span><div><h2>{editingId?'Edit Manuscript Record':'Create Manuscript Record'}</h2><p>Complete the article, source, author, and publication details.</p></div></div><form onSubmit={handleSubmit(submit)} noValidate autoComplete="off"><div className="row g-3">
    <div className="col-md-4"><label>Article Code</label><input className={`form-control ${errors.articleCode?'is-invalid':''}`} {...register('articleCode')}/><div className="invalid-feedback">{errors.articleCode?.message}</div></div><div className="col-md-8"><label>Article Title</label><input className={`form-control ${errors.articleTitle?'is-invalid':''}`} {...register('articleTitle')}/><div className="invalid-feedback">{errors.articleTitle?.message}</div></div>
    <div className="col-12"><label>Source</label><select className={`form-select ${errors.journalId?'is-invalid':''}`} {...register('journalId')}><option value="">Select source</option>{sources.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select><div className="invalid-feedback">{errors.journalId?.message}</div></div>
    <div className="col-md-5"><label>Find Subject Area</label><div className="input-group"><span className="input-group-text"><i className="bi bi-search"/></span><input type="search" className="form-control" value={subjectAreaQuery} onChange={event=>setSubjectAreaQuery(event.target.value)} placeholder="Search subject, classification, or major subject" autoComplete="off"/></div><small className="text-muted">Use keywords and the paper topic to find the best single classification.</small></div><div className="col-md-7"><label>Subject Area</label><select className={`form-select ${errors.subjectAreaId?'is-invalid':''}`} {...register('subjectAreaId')}><option value="">Select one subject area</option>{filteredSubjectAreas.map(subject=><option value={subject.id} key={subject.id}>{subject.subjectArea} — {subject.classificationName} ({subject.majorSubject})</option>)}</select><div className="invalid-feedback">{errors.subjectAreaId?.message}</div><small className="text-muted">{filteredSubjectAreas.length.toLocaleString()} matching subject area{filteredSubjectAreas.length===1?'':'s'}</small></div>
    <div className="col-12"><ManuscriptAuthorPicker value={authorAssignments} onChange={setAuthorAssignments}/></div>
    <div className="col-md-2"><label>Volume</label><input className="form-control" {...register('volume')}/></div><div className="col-md-2"><label>Issue</label><input className="form-control" {...register('issue')}/></div><div className="col-md-2"><label>Pages</label><input className="form-control" placeholder="Example: 125–138" {...register('pages')}/></div><div className="col-md-3"><label>Publication Month</label><input className="form-control" {...register('publicationMonth')}/></div><div className="col-md-3"><label>Publication Year</label><input className={`form-control ${errors.publicationYear?'is-invalid':''}`} {...register('publicationYear')}/><div className="invalid-feedback">{errors.publicationYear?.message}</div></div>
    <div className="col-md-6"><label>DOI</label><input className="form-control" {...register('doi')}/></div><div className="col-md-6"><label>Article Link</label><input className={`form-control ${errors.articleLink?'is-invalid':''}`} {...register('articleLink')}/><div className="invalid-feedback">{errors.articleLink?.message}</div></div><div className="col-12"><label>Abstract</label><textarea rows={5} className="form-control" {...register('abstract')}/></div><div className="col-12"><label>Keywords</label><textarea rows={2} className="form-control" {...register('keywords')}/></div>
    <div className="col-12">{error&&<div className="alert alert-danger py-2">{error}</div>}<div className="d-flex justify-content-end gap-2"><button type="button" className="btn btn-outline-secondary" onClick={()=>navigate('/admin/manuscripts')}>Cancel</button><button className="btn btn-primary" disabled={isSubmitting}>{isSubmitting?'Saving…':editingId?'Update Manuscript':'Save Manuscript'} <i className="bi bi-check2 ms-2"/></button></div></div>
  </div></form></div>}
  {mode==='list'&&<div className="users-table-card"><div className="table-title admin-list-title"><h3>Manuscripts</h3><AdminTableControls query={query} onQueryChange={changeQuery} placeholder="Search ID, code, title, source, subject area, authors, year, DOI" sort={sort} onSortChange={changeSort} options={[{value:'newest',label:'Newest first'},{value:'title',label:'Title A–Z'},{value:'source',label:'Source A–Z'},{value:'subject',label:'Subject Area A–Z'},{value:'year',label:'Year: Newest'},{value:'references',label:'References: High–Low'}]}/><span>{records.length} of {pagination.totalRecords}</span></div>{error&&<div className="alert alert-danger m-3">{error}</div>}{notice&&<div className="alert alert-success m-3">{notice}</div>}<div className="table-responsive"><table className="table align-middle"><thead><tr><th>Sl. No.</th><th>Manuscript</th><th>Source</th><th>Subject Area</th><th>Authors</th><th>Volume (Issue)</th><th>Pages</th><th>Year</th><th>References</th><th>Actions</th></tr></thead><tbody>{loading&&<tr><td colSpan={10} className="text-center text-muted py-4"><span className="spinner-border spinner-border-sm me-2"/>Loading manuscripts…</td></tr>}{!loading&&!records.length&&<tr><td colSpan={10} className="text-center text-muted py-4">No manuscripts found.</td></tr>}{!loading&&records.map((r,i)=><tr key={r.id}><td>{(page-1)*ADMIN_PAGE_SIZE+i+1}</td><td><b>{r.articleTitle}</b><small><code>{r.articleCode}</code> · ID {r.id}</small></td><td>{r.journalTitle}</td><td>{r.subjectArea||'—'}{r.subjectClassification&&<small>{r.subjectClassification}</small>}</td><td>{r.authors||'—'}</td><td>{r.volume||'—'}{r.issue?` (${r.issue})`:''}</td><td>{r.pages||'—'}</td><td>{r.publicationYear||'—'}</td><td><span className="article-count-badge">{r.referenceCount}</span></td><td><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-primary" title="Edit" onClick={()=>navigate(`/admin/manuscripts/addnew?edit=${r.id}`)}><i className="bi bi-pencil"/></button><button className="btn btn-sm btn-outline-danger" title="Delete" onClick={()=>remove(r)} disabled={deletingId===r.id}>{deletingId===r.id?<span className="spinner-border spinner-border-sm"/>:<i className="bi bi-trash3"/>}</button></div></td></tr>)}</tbody></table></div><AdminPagination total={pagination.totalRecords} page={page} onPageChange={setPage}/></div>}
  </section>
}
