import { useCallback, useEffect, useState } from 'react';
import { useForm, type Resolver } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useLocation, useNavigate } from 'react-router-dom';
import { api } from '../lib/auth';
import { countries } from '../data/countries';
import AdminTableControls from './AdminTableControls';
import AdminPagination from './AdminPagination';
import AuthorAffiliationPicker, { type SelectedAuthorAffiliation } from './AuthorAffiliationPicker';

type Kind='authors'|'affiliations';
type AuthorAffiliation={id:number;name:string;country:string|null;department:string|null;designation:string|null;designations:string[];startYear:number|null;endYear:number|null;papers:number};
type Author={id:number;salutation:string|null;authorName:string;department:string|null;designation:string|null;email:string|null;orcid:string|null;affiliation:string|null;country:string|null;articleCount:number;affiliations?:AuthorAffiliation[];linkedAffiliations?:SelectedAuthorAffiliation[]};
type Affiliation={id:number;universityCompany:string;cityTerritory:string;address:string;country:string;authorCount:number};
const authorSchema=z.object({salutation:z.string(),authorName:z.string().trim().min(2,'Enter the author name').max(555).refine(value=>!/(?:Ph\.?\s*D\.?|D\.?\s*Sc\.?|M\.?\s*D\.?)/i.test(value),'Do not include Ph.D, DSc, or M.D in the author name'),department:z.string().trim().max(500),designation:z.string().trim().max(500),email:z.union([z.string().trim().email('Enter a valid email'),z.literal('')]),orcid:z.string().trim().max(50)});
const affiliationSchema=z.object({universityCompany:z.string().trim().min(2,'Enter the university, institution, or company').max(500),cityTerritory:z.string().trim().max(255),address:z.string().trim().max(255),country:z.string().trim().max(255)});
type FormValues={salutation?:string;authorName?:string;department?:string;designation?:string;email?:string;orcid?:string;universityCompany?:string;cityTerritory?:string;address?:string;country?:string};

export default function ProfileDataManager({kind,mode='list'}:{kind:Kind;mode?:'list'|'form'}){
  const isAuthor=kind==='authors',base=isAuthor?'/admin/author-profiles':'/admin/affiliation-profiles',navigate=useNavigate(),location=useLocation();
  const [records,setRecords]=useState<Array<Author|Affiliation>>([]),[page,setPage]=useState(1),[totalRecords,setTotalRecords]=useState(0),[query,setQuery]=useState(''),[debouncedQuery,setDebouncedQuery]=useState(''),[sort,setSort]=useState('name'),[editingId,setEditingId]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deletingId,setDeletingId]=useState<number|null>(null),[selectedAffiliations,setSelectedAffiliations]=useState<SelectedAuthorAffiliation[]>([]);
  const resolver=zodResolver((isAuthor?authorSchema:affiliationSchema) as never) as Resolver<FormValues>;
  const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<FormValues>({resolver,defaultValues:isAuthor?{salutation:'',authorName:'',department:'',designation:'',email:'',orcid:''}:{universityCompany:'',cityTerritory:'',address:'',country:''}});
  useEffect(()=>{const timer=setTimeout(()=>{setDebouncedQuery(query);setPage(1);},300);return()=>clearTimeout(timer);},[query]);
  const load=useCallback(()=>{setLoading(true);setError('');return api.get<{profiles:Array<Author|Affiliation>;page:number;totalPages:number;totalRecords:number}>(base,{params:{q:debouncedQuery,page,sort}}).then(({data})=>{setRecords(data.profiles);setTotalRecords(data.totalRecords);}).catch(()=>setError(`Unable to load ${isAuthor?'author':'affiliation'} profiles.`)).finally(()=>setLoading(false));},[base,debouncedQuery,isAuthor,page,sort]);
  useEffect(()=>{if(mode==='list')void load();},[load,mode]);
  useEffect(()=>{if(mode!=='form')return;const id=Number(new URLSearchParams(location.search).get('edit'));if(!id){setEditingId(null);setSelectedAffiliations([]);reset(isAuthor?{salutation:'',authorName:'',department:'',designation:'',email:'',orcid:''}:{universityCompany:'',cityTerritory:'',address:'',country:''});return;}setEditingId(id);api.get<{profile:Author|Affiliation}>(`${base}/${id}`).then(({data})=>{const profile=data.profile;if(isAuthor)setSelectedAffiliations((profile as Author).linkedAffiliations||[]);reset(isAuthor?{salutation:(profile as Author).salutation||'',authorName:(profile as Author).authorName,department:(profile as Author).department||'',designation:(profile as Author).designation||'',email:(profile as Author).email||'',orcid:(profile as Author).orcid||''}:{universityCompany:(profile as Affiliation).universityCompany,cityTerritory:(profile as Affiliation).cityTerritory||'',address:(profile as Affiliation).address||'',country:(profile as Affiliation).country||''});}).catch(()=>setError('Unable to load this profile.'));},[base,isAuthor,location.search,mode,reset]);
  const submit=async(values:FormValues)=>{setError('');if(isAuthor&&!editingId&&!selectedAffiliations.length){setError('Search and select an affiliation for this author.');return;}try{const payload=isAuthor?{...values,affiliations:selectedAffiliations.map(affiliation=>({affiliationId:affiliation.id}))}:values;const response=editingId?await api.put<{message:string}>(`${base}/${editingId}`,payload):await api.post<{message:string}>(base,payload);setNotice(response.data.message);navigate(base);}catch(requestError){setError((requestError as {response?:{data?:{message?:string}}}).response?.data?.message||'Unable to save this profile.');}};
  const remove=async(record:Author|Affiliation)=>{const label=isAuthor?(record as Author).authorName:(record as Affiliation).universityCompany;if(!window.confirm(`Delete “${label}”?`))return;setDeletingId(record.id);setError('');try{const response=await api.delete<{message:string}>(`${base}/${record.id}`);setNotice(response.data.message);await load();}catch(requestError){setError((requestError as {response?:{data?:{message?:string}}}).response?.data?.message||'Unable to delete this profile.');}finally{setDeletingId(null);}};
  const title=isAuthor?'Author Profiles':'Affiliation Profiles';
  return <section><div className="manager-heading"><div><span className="eyebrow">Super Admin controls</span><h2>{mode==='form'?(editingId?'Edit ':'Add New ')+title.slice(0,-1):title}</h2><p>{isAuthor?'Manage canonical author identity, email, and ORCID records.':'Manage universities, institutions, companies, addresses, and countries.'}</p></div>{mode==='list'?<button className="btn btn-primary" onClick={()=>navigate(`${base}/addnew`)}><i className="bi bi-plus-lg me-2"/>Add New</button>:<button className="btn btn-outline-secondary" onClick={()=>navigate(base)}><i className="bi bi-arrow-left me-2"/>Back to list</button>}</div>
  {mode==='form'&&<div className="admin-form-card"><div className="admin-panel-heading"><span className="form-icon"><i className={`bi ${isAuthor?'bi-person-vcard':'bi-building'}`}/></span><div><h2>{editingId?'Edit':'Create'} {isAuthor?'Author':'Affiliation'} Profile</h2><p>Complete the profile information below.</p></div></div><form onSubmit={handleSubmit(submit)} noValidate autoComplete="off"><div className="row g-3">{isAuthor?<>
    {editingId&&<div className="col-md-3"><label>Author ID</label><input className="form-control" value={editingId} readOnly aria-readonly="true"/></div>}<div className="col-md-3"><label>Salutation</label><select className="form-select" {...register('salutation')}><option value="">Select</option>{['Mr.','Dr.','Prof. Dr.','Ms.','Mrs.','Er.'].map(value=><option key={value}>{value}</option>)}</select></div><div className={editingId?'col-md-6':'col-md-9'}><label>Author Name</label><input className={`form-control ${errors.authorName?'is-invalid':''}`} placeholder="Name only — do not include Ph.D, DSc, or M.D" {...register('authorName')}/><div className="invalid-feedback">{errors.authorName?.message}</div></div><div className="col-md-6"><label>Email</label><input type="email" className={`form-control ${errors.email?'is-invalid':''}`} {...register('email')}/><div className="invalid-feedback">{errors.email?.message}</div></div><div className="col-md-6"><label>ORCID</label><input className="form-control" placeholder="0000-0000-0000-0000" {...register('orcid')}/></div><div className="col-md-6"><label>Department</label><input className="form-control" placeholder="Enter department" autoComplete="off" {...register('department')}/></div><div className="col-md-6"><label>Designation</label><input className="form-control" placeholder="Enter designation" autoComplete="off" {...register('designation')}/></div><div className="col-12"><AuthorAffiliationPicker value={selectedAffiliations} onChange={setSelectedAffiliations}/></div>
  </>:<><div className="col-md-8"><label>University / Institution / Company</label><input className={`form-control ${errors.universityCompany?'is-invalid':''}`} placeholder="Institution name only" {...register('universityCompany')}/><div className="invalid-feedback">{errors.universityCompany?.message}</div></div><div className="col-md-4"><label>City / Territory</label><input className="form-control" placeholder="City or territory" {...register('cityTerritory')}/></div><div className="col-md-4"><label>Country</label><select className="form-select" {...register('country')}><option value="">Select country</option>{countries.map(country=><option key={country}>{country}</option>)}</select></div><div className="col-md-8"><label>Address</label><textarea rows={3} className="form-control" {...register('address')}/></div></>}
    <div className="col-12">{error&&<div className="alert alert-danger py-2">{error}</div>}<div className="d-flex justify-content-end gap-2"><button type="button" className="btn btn-outline-secondary" onClick={()=>navigate(base)}>Cancel</button><button className="btn btn-primary" disabled={isSubmitting}>{isSubmitting?'Saving…':editingId?'Update Profile':'Save Profile'}</button></div></div></div></form></div>}
  {mode==='list'&&<div className="users-table-card"><div className="table-title admin-list-title"><h3>{title}</h3><AdminTableControls query={query} onQueryChange={setQuery} placeholder={isAuthor?'Search ID, author, email, ORCID':'Search ID, institution, city, address, country'} sort={sort} onSortChange={value=>{setSort(value);setPage(1);}} options={isAuthor?[{value:'name',label:'Author A–Z'},{value:'newest',label:'Newest first'},{value:'email',label:'Email A–Z'},{value:'articles',label:'Articles: High–Low'}]:[{value:'name',label:'Institution A–Z'},{value:'newest',label:'Newest first'},{value:'country',label:'Country A–Z'},{value:'authors',label:'Authors: High–Low'}]}/><span>{totalRecords.toLocaleString()} records</span></div>{error&&<div className="alert alert-danger m-3">{error}</div>}{notice&&<div className="alert alert-success m-3">{notice}</div>}<div className="table-responsive"><table className="table align-middle"><thead>{isAuthor?<tr><th>ID</th><th>Author Name</th><th>Email</th><th>Affiliation / Country</th><th>Articles</th><th>Actions</th></tr>:<tr><th>ID</th><th>University / Institution / Company</th><th>City / Territory</th><th>Address</th><th>Country</th><th>Authors</th><th>Actions</th></tr>}</thead><tbody>{loading?<tr><td colSpan={isAuthor?6:7} className="text-center py-4">Loading profiles…</td></tr>:records.map(record=>isAuthor?<tr key={record.id}><td><code>{record.id}</code></td><td><b>{[(record as Author).salutation,(record as Author).authorName].filter(Boolean).join(' ')}</b></td><td>{(record as Author).email||'—'}</td><td>{(record as Author).affiliation||'—'}<small>{(record as Author).country||'—'}</small></td><td>{(record as Author).articleCount}</td><td><Actions id={record.id} base={base} deleting={deletingId===record.id} navigate={navigate} remove={()=>remove(record)}/></td></tr>:<tr key={record.id}><td><code>{record.id}</code></td><td><b>{(record as Affiliation).universityCompany}</b></td><td>{(record as Affiliation).cityTerritory||'—'}</td><td>{(record as Affiliation).address||'—'}</td><td>{(record as Affiliation).country||'—'}</td><td>{(record as Affiliation).authorCount}</td><td><Actions id={record.id} base={base} deleting={deletingId===record.id} navigate={navigate} remove={()=>remove(record)}/></td></tr>)}{!loading&&!records.length&&<tr><td colSpan={isAuthor?6:7} className="text-center text-muted py-4">No profiles found.</td></tr>}</tbody></table></div><AdminPagination total={totalRecords} page={page} onPageChange={setPage}/></div>}
  </section>;
}

function Actions({id,base,deleting,navigate,remove}:{id:number;base:string;deleting:boolean;navigate:(path:string)=>void;remove:()=>void}){return <div className="d-flex gap-2"><button className="btn btn-sm btn-outline-primary" title="Edit" onClick={()=>navigate(`${base}/addnew?edit=${id}`)}><i className="bi bi-pencil"/></button><button className="btn btn-sm btn-outline-danger" title="Delete" disabled={deleting} onClick={remove}>{deleting?<span className="spinner-border spinner-border-sm"/>:<i className="bi bi-trash3"/>}</button></div>}
